#name: Docker Image CI
#
#on: [push]
#
#jobs:
#
#  build:
#
#    runs-on: ubuntu-latest
#
#
#    steps:
#    - uses: actions/checkout@v2
#      #- name: Build the Docker image
#      #- run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#    - uses: mr-smithers-excellent/docker-build-push@v2
#      with:
#        registry: docker.io
#        image: cloudfish/k8s-toolbox
#        tag: latest
#        dockerfile: Dockerfile
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}


name: Backend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  #  ci:
  #    runs-on: ubuntu-latest
  #    container:
  #      image: k8s-toolbox
  #
  #    steps:
  #      - uses: actions/checkout@v1
  #      - name: Install & Tests
  #        run: |
  #          npm install
  #          npm test
  cd:
    runs-on: ubuntu-latest
    #needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        #run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} -p --password-stdin  docker.io
      - name: Build
        run: docker build -t k8s-toolbox .
      - name: Tags
        run: |
          docker tag k8s-toolbox ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:${{ github.sha }}
          docker tag k8s-toolbox ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:latest

