name: Docker Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 0 21 * * *

jobs:

  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      - name: Build
        run: docker build -t k8s-toolbox .
      - name: Tags
        run: |
          docker tag k8s-toolbox ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:${{ github.sha }}
          docker tag k8s-toolbox ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/k8s-toolbox:latest

